### PR TITLE
Improvements to the IIIF API translation

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by cbeer** [comment]
@jronallo ping?

**Comment by cbeer** [comment]
Actually, hold off on this.. I'm still not sure the "make it fit within" directive is right.

**Comment by cbeer** [comment]
:ok_hand: , it should be all good now.

**Comment by cbeer** [comment]
@jronallo :question:

**Comment by jronallo** [comment]
Thanks @cbeer !

**Pull request merged**
